package use_case.recommend;

import data_access.EdamamApiAccess;
import org.junit.Test;
import use_case.signup.SignupOutputData;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class RecommendInteractorTest {

    @Test
    public void successTest() {
        // create parameters needed for input data
        ArrayList<String> diet = new ArrayList<String>();
        diet.add("low-fat");
        ArrayList<String> health = new ArrayList<String>();
        health.add("vegetarian");
        String mealType = "Breakfast";


        RecommendInputData inputData = new RecommendInputData(diet, health, mealType);
        RecommendDataAccessInterface recommendDataAccessObject = new EdamamApiAccess();

        RecommendOutputBoundary successPresenter = new RecommendOutputBoundary() {
            @Override
            public void prepareSuccessView(RecommendOutputData outputData) {
                // check that the link generated by the api is a valid link
                assertTrue(outputData.getRecommendLink().contains("http://www.edamam.com/recipe/"));//all links from api start this way
            }

            @Override
            public void prepareFailView(String error) {
                fail("Use case failure is unexpected");
            }
        };

        RecommendInputBoundary interactor = new RecommendInteractor(recommendDataAccessObject, successPresenter);
        interactor.execute(inputData);

    }

}